/* BASEERAH: same-origin API, safe DOM rendering, optional device history. */
'use strict';
const pageMap={'compare-r':'compare-result','detect-r':'detect-result','home':'../index'};
const basePath=location.pathname.includes('/pages/')?'':'pages/';
function go(id){location.href=id==='home'?(basePath?'index.html':'../index.html'):basePath+(pageMap[id]||id)+'.html';}
function goBack(){history.length>1?history.back():go('home');}
const $=id=>document.getElementById(id);
function node(tag,text,cls){const el=document.createElement(tag);if(text!=null)el.textContent=String(text);if(cls)el.className=cls;return el;}
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{throw new Error('تعذر الحفظ على الجهاز. تحقق من مساحة التخزين وإعدادات المتصفح.');}}
function safeLink(url,label){try{const u=new URL(url);if(u.protocol!=='https:')return null;const a=node('a',label,'btn ghost');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a;}catch{return null;}}
function percent(v){return Number.isFinite(v)?Math.round(v*100)+'%':'غير متاح';}
function technicalScore(v){return Number.isFinite(v)?Math.max(-1,Math.min(1,v)).toFixed(2)+' من 1.00':'غير متاح';}
async function api(path,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),300000);try{const r=await fetch(path,{method:body?'POST':'GET',body,headers:typeof body==='string'?{'Content-Type':'application/json'}:undefined,signal:controller.signal});const data=await r.json().catch(()=>({}));if(!r.ok){const messages={413:'حجم الملف يتجاوز الحد المسموح.',415:'صيغة الملف غير مدعومة.',422:'تعذر تحليل المدخل. تحقق من الملف وتجهيز النماذج.',500:'تعذر إكمال التحليل في الخادم.'};throw new Error(messages[r.status]||'تعذر إكمال الطلب. تحقق من الخادم والمدخلات.');}return data;}catch(e){if(e.name==='AbortError')throw new Error('استغرق التحليل وقتًا طويلًا. جرّب مقطعًا أقصر.');if(e instanceof TypeError)throw new Error('تعذر الاتصال بالخادم. افتح الواجهة من /ui/ بعد تشغيل بصيرة.');throw e;}finally{clearTimeout(timer);}}
function file(id,kind='audio'){const f=$(id).files[0];if(!f||!f.size)throw new Error('اختر ملفًا غير فارغ أولًا.');const image=kind==='image';if(!(image?/\.(jpg|jpeg|png|webp)$/i:/\.(mp3|wav|m4a|ogg|webm)$/i).test(f.name))throw new Error('صيغة الملف غير مدعومة.');if(f.size>(image?5:25)*1024*1024)throw new Error(image?'الحد الأقصى للصورة 5 MB.':'الحد الأقصى للصوت 25 MB.');return f;}
function formFile(form,key,id,kind){const f=file(id,kind);const types={mp3:'audio/mpeg',wav:'audio/wav',m4a:'audio/mp4',ogg:'audio/ogg',webm:'audio/webm',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp'};form.append(key,new Blob([f],{type:types[f.name.split('.').pop().toLowerCase()]}),f.name);return f;}
function remember(result,kind){const record={id:crypto.randomUUID(),at:new Date().toISOString(),kind,result};sessionStorage.setItem('baseerahCurrent',JSON.stringify(record));if(read('baseerahKeep',false)){const list=read('baseerahHistory',[]);list.unshift(record);write('baseerahHistory',list.slice(0,30));}return record;}
function bindForm(id,run){const f=$(id);if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const b=f.querySelector('button'),s=f.querySelector('.status');b.disabled=true;s.className='status';s.textContent='جارٍ التحليل… قد يستغرق تحميل النماذج لأول مرة عدة دقائق.';try{await run();}catch(err){console.error('BASEERAH request failed',err);s.textContent=err.message;s.className='status error';}finally{b.disabled=false;}});}
function card(title,text){const c=node('section',null,'card');c.append(node('h2',title));if(text)c.append(node('p',text));return c;}
function current(){try{return JSON.parse(sessionStorage.getItem('baseerahCurrent'));}catch{return null;}}
function renderResult(){const target=$('result');if(!target)return;const record=current();if(!record){target.append(card('لا توجد نتيجة','ابدأ عملية تحقق أولًا.'));const b=node('button','تحقق جديد','btn');b.onclick=()=>go('detect');target.append(b);return;}const r=record.result,c=r.content_verification||r;
 if(record.kind==='compare'){const t={strong_match:'تشابه صوتي مرتفع — الهوية غير مؤكدة',uncertain:'المقارنة غير حاسمة',low_similarity:'لم يتأكد تطابق المتحدثين'};const d={strong_match:'تجاوز المؤشر الحد التجريبي للتشابه المرتفع؛ لا يؤكد هوية المتحدث أو سلامة التسجيل من التعديل.',uncertain:'المؤشر قريب من منطقة القرار؛ يلزم تسجيل أوضح أو مراجعة إضافية.',low_similarity:'المؤشر دون حد المطابقة التجريبي؛ لا يؤكد أن المتحدث في التسجيلين واحد.'};const box=card(t[r.speaker_interpretation]||'نتيجة المقارنة',d[r.speaker_interpretation]||'هذه نتيجة تقنية مساعدة وليست إثباتًا نهائيًا للهوية.');box.append(node('p','مؤشر تشابه البصمة: '+technicalScore(r.speaker_similarity),'score'));box.append(node('p','حد المطابقة التجريبي: '+Number(r.decision_threshold??.95).toFixed(2)+' من 1.00','muted-copy'));box.append(node('p','المؤشر درجة تشابه تقنية، وليس احتمالًا إحصائيًا لهوية المتحدث.','muted-copy'));target.append(box);}else{
 const found=c.status==='evidence_found';const box=card(found?'تم العثور على دليل ذي صلة':'الدليل غير كافٍ',found?'راجع المصدر والنص المطابق والسياق قبل النشر.':'لم تتوفر أدلة كافية لتأكيد المحتوى. لا يعني ذلك أنه مزيف.');box.append(node('span',r.review_status==='needs_review'?'يحتاج مراجعة بشرية':found?'دليل مسترجع':'غير محسوم','chip'+(r.review_status==='needs_review'?' review':'')));if(c.evidence_score)box.append(node('p','درجة الاسترجاع التقنية: '+percent(c.evidence_score.final_score)));box.append(node('p','درجة الاسترجاع ليست احتمالًا لصحة المحتوى.','muted-copy'));target.append(box);
 target.append(card('النص المُدخل أو المستخرج',c.query||'لم يتوفر نص قابل للتحقق.'));
 if(found&&c.source){const source=card(c.source.document_title,c.source.source_name);const link=safeLink(c.source.source_url,'فتح المصدر الأصلي');if(link)source.append(link);target.append(source);if(c.quote_excerpt){const e=c.quote_excerpt;const excerpt=card(e.is_partial_chunk?'الاقتباس جزء من النص المفهرس':'تطابق لفظي مع النص المفهرس','تم تحديد الكلمات داخل المصدر بعد تجاهل التشكيل وعلامات الترقيم.');for(const [title,text] of [['قبل الاقتباس داخل النص',e.before],['الاقتباس المحدد',e.matched_text],['بعد الاقتباس داخل النص',e.after]]){excerpt.append(node('h3',title),node('p',text?.trim()||'لا يوجد نص إضافي داخل هذا الجزء المفهرس.'));}excerpt.append(node('p','هذه مطابقة نصية؛ لا تثبت أصل التسجيل الصوتي أو وجود قص أو تحريف في المعنى.','notice'));target.append(excerpt);}const context=card('السياق الأصلي');for(const [key,title] of [['previous','قبل الاقتباس'],['current','النص المطابق'],['next','بعد الاقتباس']]){context.append(node('h3',title));context.append(node('p',c.context_trace?.[key]?.original_text||(key==='current'?c.source.original_text:null)||'غير متاح في المصدر المفهرس.','context'));}target.append(context);}
 const a=r.audio_authenticity;if(a){const sp=a.speaker_identity||{},sy=a.synthetic_voice||{};const speaker=card('هوية المتحدث',sp.interpretation==='trusted_match'?'تطابق مع صوت مرجعي': 'لم تتأكد هوية المتحدث');if(sp.interpretation==='trusted_match')speaker.append(node('p',sp.best_match?.speaker_name));speaker.append(node('p','مؤشر تشابه البصمة: '+technicalScore(sp.best_score)));speaker.append(node('p','درجة تشابه تقنية وليست احتمالًا إحصائيًا للهوية.','muted-copy'));target.append(speaker);const labels={likely_natural:'لم يرصد النموذج مؤشرات قوية لصوت صناعي',likely_synthetic:'رصد النموذج مؤشرات لصوت صناعي',uncertain:'نتيجة الصوت الصناعي غير حاسمة'};const synthetic=card('مؤشرات الصوت الصناعي',labels[sy.interpretation]||'التحليل غير متاح');synthetic.append(node('p','مؤشر النموذج للصوت الصناعي: '+technicalScore(sy.synthetic_score)));synthetic.append(node('p','تحليل تجريبي لأربع ثوانٍ، ودرجاته غير معايرة كاحتمالات.','muted-copy'));target.append(synthetic,card('تحليل القص والدمج','غير مفعّل في هذه النسخة.'));if(r.review_status==='needs_review')target.append(card('المراجعة البشرية','تحتاج هذه النتيجة مراجعة مختص بسبب عدم اكتمال أو تعارض الإشارات. لم يُرسل طلب مراجعة تلقائيًا.'));}
 }
 const actions=node('div',null,'actions');const save=node('button','حفظ النتيجة','btn ghost');save.onclick=()=>{try{const list=read('baseerahSaved',[]);if(!list.some(x=>x.id===record.id)){list.unshift(record);write('baseerahSaved',list.slice(0,30));}save.textContent='تم الحفظ على الجهاز';}catch(e){save.textContent=e.message;}};const again=node('button','تحقق جديد','btn');again.onclick=()=>go(record.kind==='compare'?'compare':record.kind==='text'?'quote':record.kind==='image'?'image':'detect');actions.append(save,again);target.append(actions);
}
function renderHistory(id,saved=false){const t=$(id);if(!t)return;const list=read(saved?'baseerahSaved':'baseerahHistory',[]);if(!list.length){t.append(card('لا توجد نتائج محفوظة',saved?'احفظ نتيجة من صفحة التحليل.':'يمكن تفعيل حفظ السجل من الإعدادات.'));return;}for(const entry of list){const c=card(({audio:'تحقق صوتي',image:'تحقق من صورة',text:'تحقق نصي',compare:'مقارنة صوتين'})[entry.kind]||'نتيجة',new Date(entry.at).toLocaleString('ar-SA'));const b=node('button','عرض النتيجة','btn ghost');b.onclick=()=>{sessionStorage.setItem('baseerahCurrent',JSON.stringify(entry));go(entry.kind==='compare'?'compare-r':'detect-r');};c.append(b);t.append(c);}}
const guides=[['المصدر قبل النشر','افتح رابط المصدر، وراجع عنوانه وصاحب المحتوى. وجود تشابه لفظي أو دلالي لا يثبت صحة النسبة.'],['السياق قبل الاقتباس','اقرأ الكلام السابق واللاحق للنص المطابق. قد يكون السياق غير متاح عندما تكون قاعدة المعرفة محدودة.'],['فهم نتائج الصوت','هوية المتحدث ومؤشرات الصوت الصناعي إشارتان مستقلتان. التشابه لا يثبت الأصالة، وعدم تأكيد الهوية لا يعني التزييف.'],['المشاركة المسؤولة','عندما تكون الأدلة غير كافية، توقف عن تأكيد النسبة وارجع إلى جهة أو مختص موثوق.']];
function renderGuides(){const t=$('guideList');if(!t)return;t.replaceChildren();for(const [title,body] of guides.filter(g=>g.join(' ').includes($('guideSearch').value))){const b=node('button',title,'btn ghost');b.onclick=()=>{sessionStorage.setItem('baseerahGuide',JSON.stringify({title,body}));go('detail');};t.append(b);}}
document.addEventListener('DOMContentLoaded',()=>{
 for(const input of document.querySelectorAll('.upload input')){input.addEventListener('change',()=>{input.parentElement.querySelector('.file-label').textContent=input.files[0]?.name||'اختر ملفًا';});const label=input.parentElement;label.addEventListener('dragover',e=>e.preventDefault());label.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files.length){input.files=e.dataTransfer.files;input.dispatchEvent(new Event('change'));}});}
 bindForm('audioForm',async()=>{const f=new FormData();formFile(f,'audio','audio');remember(await api('/verify/audio/full',f),'audio');go('detect-r');});
 bindForm('imageForm',async()=>{const f=new FormData();formFile(f,'image','image','image');remember(await api('/verify/image',f),'image');go('detect-r');});
 bindForm('textForm',async()=>{const text=$('quoteText').value.trim();if(!text)throw new Error('أدخل نصًا للتحقق.');remember(await api('/verify/text',JSON.stringify({text})),'text');go('detect-r');});
 bindForm('compareForm',async()=>{const f=new FormData();formFile(f,'reference_audio','reference');formFile(f,'candidate_audio','candidate');remember(await api('/verify/speaker',f),'compare');go('compare-r');});
 bindForm('fingerprintCheckForm',async()=>{const f=new FormData();formFile(f,'audio','fingerprintCheck');const r=await api('/tools/fingerprint/check',f);document.querySelector('#fingerprintCheckForm .status').textContent=r.match_found?'تطابق الملف حرفيًا مع البصمة المسجلة: '+r.title:'لم توجد بصمة مطابقة. هذا لا يثبت التزييف أو صحة المحتوى.';});
 bindForm('fingerprintForm',async()=>{const f=new FormData();formFile(f,'audio','fingerprint');f.append('title',$('documentName').value.trim());sessionStorage.setItem('baseerahFingerprint',JSON.stringify(await api('/tools/fingerprint',f)));go('doc-confirm');});
 if($('fingerprintResult')){let r;try{r=JSON.parse(sessionStorage.getItem('baseerahFingerprint'));}catch{}const t=$('fingerprintResult');if(!r)t.append(card('لا يوجد سجل','سجّل ملفًا أولًا.'));else{const c=card(r.title,'تم حساب بصمة الملف وتسجيلها في خادم النموذج.');c.append(node('p',r.sha256,'hash'),node('p',new Date(r.created_at).toLocaleString('ar-SA')),node('p','البصمة تثبت تطابق البايتات فقط؛ لا تثبت هوية الناشر أو صحة المحتوى.','notice'));t.append(c);}}
 renderResult();renderHistory('historyList');renderHistory('savedList',true);
 if($('sourcesList'))api('/tools/sources').then(r=>{for(const s of r.sources){const c=card(s.source_name,s.document_title+' · '+s.chunk_count+' مقاطع');const a=safeLink(s.source_url,'فتح المصدر');if(a)c.append(a);$('sourcesList').append(c);}if(!r.sources.length)$('sourcesList').append(card('لا توجد مصادر مفهرسة'));}).catch(e=>$('sourcesList').append(card('تعذر تحميل المصادر',e.message)));
 if($('radarList')){const list=read('baseerahHistory',[]);$('radarList').append(card('ملخص محلي',`عمليات محفوظة: ${list.length} · نتائج تحتاج مراجعة: ${list.filter(x=>x.result.review_status==='needs_review').length}`),card('نطاق البيانات','هذه إحصاءات هذا الجهاز فقط. لا يتصل النموذج بمنصات التواصل ولا يرصد الانتشار الخارجي.'));
 }
 if($('keepHistory')){$('keepHistory').checked=read('baseerahKeep',false);$('keepHistory').onchange=()=>{try{write('baseerahKeep',$('keepHistory').checked);}catch(e){document.querySelector('.status').textContent=e.message;}};$('clearHistory').onclick=()=>{localStorage.removeItem('baseerahHistory');localStorage.removeItem('baseerahSaved');sessionStorage.removeItem('baseerahCurrent');document.querySelector('.status').textContent='تم مسح النتائج المحفوظة.';};}
 renderGuides();$('guideSearch')?.addEventListener('input',renderGuides);if($('detailBody')){try{const g=JSON.parse(sessionStorage.getItem('baseerahGuide'));$('detailTitle').textContent=g?.title||'دليل الاستخدام';$('detailBody').textContent=g?.body||'اختر دليلًا من صفحة الأدلة.';}catch{$('detailBody').textContent='تعذر تحميل الدليل.';}}
 document.querySelectorAll('[onclick],.upload').forEach(el=>{if(['DIV'].includes(el.tagName)){el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});}});
});
