const {parseHTML}=require('linkedom');
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=require('path').resolve(__dirname,'../Frontend /baseerah-separated');
const script=fs.readFileSync(root+'/js/app.js','utf8');
const evidence={status:'evidence_found',query:'نص الاختبار',evidence_score:{final_score:.8},source:{document_title:'مصدر <script>bad()</script>',source_name:'موسوعة',source_url:'https://example.com',original_text:'النص المطابق'},context_trace:{previous:{original_text:'قبل'},current:{original_text:'المطابق'},next:{original_text:'بعد'}}};
const full={content_verification:evidence,review_status:'needs_review',audio_authenticity:{speaker_identity:{interpretation:'unknown',best_score:.7,best_match:{speaker_name:'غير مؤكد'}},synthetic_voice:{interpretation:'uncertain',synthetic_score:.4}}};
function setup(page,record){const {window}=parseHTML(fs.readFileSync(root+'/'+page,'utf8'));const store=new Map();const local=new Map();if(record)store.set('baseerahCurrent',JSON.stringify(record));const storage=m=>({getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)});const requests=[];const context={document:window.document,location:{pathname:'/ui/'+page,href:''},history:{length:1,back(){}},localStorage:storage(local),sessionStorage:storage(store),crypto:require('crypto').webcrypto,URL,Blob,FormData,AbortController,setTimeout,clearTimeout,console,Event:window.Event,fetch:async(path,opts)=>{requests.push({path,opts});return {ok:true,json:async()=>path==='/tools/sources'?{sources:[{source_name:'مصدر',document_title:'عنوان',chunk_count:1,source_url:'https://example.com'}]}:path==='/verify/audio/full'?full:path==='/verify/speaker'?{speaker_similarity:.96,speaker_interpretation:'strong_match',decision_threshold:.95}:evidence};}};vm.createContext(context);vm.runInContext(script,context);window.document.dispatchEvent(new window.Event('DOMContentLoaded'));return {window,context,requests};}
async function settle(){for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));}
(async()=>{
for(const page of ['index.html',...fs.readdirSync(root+'/pages').filter(f=>f.endsWith('.html')).map(f=>'pages/'+f)]){setup(page);await settle();}
for(const [page,form,id,path,kind] of [['pages/quote.html','textForm','quoteText','/verify/text','text'],['pages/image.html','imageForm','image','/verify/image','image'],['pages/detect.html','audioForm','audio','/verify/audio/full','audio'],['pages/compare.html','compareForm','reference','/verify/speaker','compare']]){const x=setup(page);if(kind==='text')x.window.document.getElementById(id).value='نص';else{x.window.document.getElementById(id).files=[new File(['bytes'],kind==='image'?'clip.png':'clip.wav')];if(kind==='compare')x.window.document.getElementById('candidate').files=[new File(['bytes'],'clip.wav')];}x.window.document.getElementById(form).dispatchEvent(new x.window.Event('submit',{cancelable:true}));await settle();assert.equal(x.requests[0].path,path);assert(x.context.sessionStorage.getItem('baseerahCurrent'));assert(x.context.location.href.endsWith('result.html'));}
let x=setup('pages/detect-result.html',{id:'1',kind:'audio',result:full});assert(x.window.document.body.textContent.includes('نص الاختبار'));assert(x.window.document.body.textContent.includes('المطابق'));assert(!x.window.document.querySelector('#result script'));assert(!x.window.document.body.textContent.includes('غير مؤكد'));const b=x.window.document.querySelector('.actions button');b.click();assert(x.context.localStorage.getItem('baseerahSaved'));
	x=setup('pages/detect-result.html',{id:'2',kind:'text',result:{...evidence,status:'insufficient_evidence'}});assert(!x.window.document.body.textContent.includes('فتح المصدر الأصلي'));
	x=setup('pages/compare-result.html',{id:'3',kind:'compare',result:{speaker_similarity:.71,speaker_interpretation:'low_similarity',decision_threshold:.95}});assert(x.window.document.body.textContent.includes('لم يتأكد تطابق المتحدثين'));assert(x.window.document.body.textContent.includes('0.71 من 1.00'));assert(x.window.document.body.textContent.includes('حد المطابقة التجريبي: 0.95'));assert(!x.window.document.body.textContent.includes('71%'));
	x=setup('pages/compare-result.html',{id:'4',kind:'compare',result:{speaker_similarity:.922,speaker_interpretation:'uncertain',decision_threshold:.95}});assert(x.window.document.body.textContent.includes('المقارنة غير حاسمة'));assert(!x.window.document.body.textContent.includes('92%'));
	x=setup('pages/compare-result.html',{id:'5',kind:'compare',result:{speaker_similarity:.977,speaker_interpretation:'strong_match',decision_threshold:.95}});assert(x.window.document.body.textContent.includes('الهوية غير مؤكدة'));assert(x.window.document.body.textContent.includes('لا يؤكد هوية المتحدث'));
	x=setup('pages/detect-result.html',{id:'6',kind:'text',result:{...evidence,quote_excerpt:{is_partial_chunk:true,before:'سياق سابق',matched_text:'<script>bad()</script>',after:'سياق لاحق'}}});assert(x.window.document.body.textContent.includes('الاقتباس جزء من النص المفهرس'));assert(x.window.document.body.textContent.includes('سياق سابق'));assert(x.window.document.body.textContent.includes('سياق لاحق'));assert(x.window.document.body.textContent.includes('لا تثبت أصل التسجيل الصوتي'));assert(!x.window.document.querySelector('#result script'));
	console.log('PASS: 19 pages initialize; 4 forms use correct APIs; result signals, technical score display, XSS-safe text, abstention and saving verified.');
})().catch(e=>{console.error(e);process.exit(1);});
